spring.application.name=Talent-Acquisition-System
# MongoDB configuration
# MongoDB connection properties
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=Talent-Acquisition-System
