package com.tas.enums;

public enum ApplicationStatus {
    APPLIED, REVIEWED, SHORTLISTED, REJECTED, 
    SCREENING, PHONE_INTERVIEW, TECHNICAL_INTERVIEW, 
    FINAL_INTERVIEW, OFFER_EXTENDED, HIRED, WITHDRAWN
}